Repository ArmDeveloperEcosystem/arm-learning-paths, pull requests merged in 2025-05, with the labels that each got.

#1883 [New] Add a LP on accelerating a Voice Assistant with KleidiAI and SME2.
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/1-prerequisites.md
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/2-overview.md
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/3-build.md
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/4-run.md
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/5-kleidiai.md
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/_index.md
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/_next-steps.md
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/_review.md
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/build_project.png
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/build_success.png
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/open_project.png
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/overview.png
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/upload.png
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/voice_assistant_view1.png
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/voice_assistant_view2.png
  content/learning-paths/mobile-graphics-and-gaming/voice-assistant/voice_assistant_view3.png
  data/stats_current_test_info.yml
Labels: tech_review

#1929 [New] Add a LP on accelerating AI Camera pipelines with KleidiAI and KleidiCV
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/1-prerequisites.md
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/2-overview.md
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/3-build.md
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/4-run.md
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/5-performances.md
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/_index.md
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/_next-steps.md
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/_review.md
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/blur_pipeline.png
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/lle_pipeline.png
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/test_input2.png
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/test_output2.png
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/test_output2_lime.png
Labels: editorial_review

#1945 Add migrate-ease LP
  assets/contributors.csv
  content/learning-paths/servers-and-cloud-computing/migrate-ease/1_codescanning.md
  content/learning-paths/servers-and-cloud-computing/migrate-ease/2_migrate_ease_spec.md
  content/learning-paths/servers-and-cloud-computing/migrate-ease/3_migrate_ease_run.md
  content/learning-paths/servers-and-cloud-computing/migrate-ease/4_migrate_ease_analysis.md
  content/learning-paths/servers-and-cloud-computing/migrate-ease/_index.md
  content/learning-paths/servers-and-cloud-computing/migrate-ease/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/migrate-ease/web_ui_index.jpg
  content/learning-paths/servers-and-cloud-computing/migrate-ease/web_ui_result.jpg
Labels: ACM, tech_review

#1953 Analyse-cache-behaviour-with-perf-c2c-on-Arm
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/_index.md
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/false_sharing_diagram.png
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/how-to-1.md
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/how-to-2.md
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/how-to-3.md
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/how-to-4.md
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/perf-c2c-record.png
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/perf-c2c.gif
  content/learning-paths/servers-and-cloud-computing/false-sharing-arm-spe/perf-record-error-skid.png
Labels: ACM, awaiting_tech_review

#1972 Increasing Linux Kernel Page Size on Arm
  content/learning-paths/servers-and-cloud-computing/arm_linux_page_size/_index.md
  content/learning-paths/servers-and-cloud-computing/arm_linux_page_size/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/arm_linux_page_size/centos.md
  content/learning-paths/servers-and-cloud-computing/arm_linux_page_size/debian.md
  content/learning-paths/servers-and-cloud-computing/arm_linux_page_size/images/pte.png
  content/learning-paths/servers-and-cloud-computing/arm_linux_page_size/overview.md
  content/learning-paths/servers-and-cloud-computing/arm_linux_page_size/ubuntu.md
Labels: ACM, awaiting_tech_review
