Repository ArmDeveloperEcosystem/arm-learning-paths, pull requests merged in 2025-04, with the labels that each got.

#1751 Learn to Optimize C++ Loops with Size Context - LP
  content/learning-paths/cross-platform/cpp-loop-size-context/Example.md
  content/learning-paths/cross-platform/cpp-loop-size-context/Introduction.md
  content/learning-paths/cross-platform/cpp-loop-size-context/_index.md
  content/learning-paths/cross-platform/cpp-loop-size-context/_next-steps.md
  content/learning-paths/cross-platform/cpp-loop-size-context/providing-inside-knowledge.md
Labels: ACM, awaiting_tech_review

#1838 GitHub Windows Arm runner LP
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/_images/actions.png
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/_images/capacity.png
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/_images/cpuinfo.png
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/_images/new-runner.png
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/_images/platform.png
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/_images/size.png
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/_images/win_image.png
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/_index.md
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/_next-steps.md
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/automate-win-app.md
  content/learning-paths/laptops-and-desktops/gh-arm-runners-win/introduction.md
Labels: tech_review

#1853 New install guide for nerdctl and containerd
  content/install-guides/nerdctl.md
Labels: editorial_review

#1847 Use GitHub Copilot to write NEON intrinsics
  content/learning-paths/cross-platform/adler32/_index.md
  content/learning-paths/cross-platform/adler32/_next-steps.md
  content/learning-paths/cross-platform/adler32/about-2.md
  content/learning-paths/cross-platform/adler32/build-6.md
  content/learning-paths/cross-platform/adler32/makefile-5.md
  content/learning-paths/cross-platform/adler32/more-11.md
  content/learning-paths/cross-platform/adler32/neon-7.md
  content/learning-paths/cross-platform/adler32/neon-debug-9.md
  content/learning-paths/cross-platform/adler32/neon-run-8.md
  content/learning-paths/cross-platform/adler32/simple-c-3.md
  content/learning-paths/cross-platform/adler32/summary-10.md
  content/learning-paths/cross-platform/adler32/test-prog-4.md
Labels: ACM, editorial_review

#1815 Quantize and Run a Large Language Model using vLLM on Arm Servers
  content/learning-paths/servers-and-cloud-computing/vLLM-quant/1-overview.md
  content/learning-paths/servers-and-cloud-computing/vLLM-quant/2-quantize-model.md
  content/learning-paths/servers-and-cloud-computing/vLLM-quant/3-run-benchmark.md
  content/learning-paths/servers-and-cloud-computing/vLLM-quant/_index.md
  content/learning-paths/servers-and-cloud-computing/vLLM-quant/_next-steps.md
  data/stats_weekly_data.yml
Labels: ACM, tech_review

#1809 [CSEREQ-1257] Learning Path Request to Showcase performance uplift of Kleidi for WoA ONNX Runtime
  content/learning-paths/laptops-and-desktops/win_on_arm_build_onnxruntime/1-dev-env-setup.md
  content/learning-paths/laptops-and-desktops/win_on_arm_build_onnxruntime/2-build-onnxruntime.md
  content/learning-paths/laptops-and-desktops/win_on_arm_build_onnxruntime/3-build-onnxruntime-generate-api.md
  content/learning-paths/laptops-and-desktops/win_on_arm_build_onnxruntime/4-run-benchmark-on-WoA.md
  content/learning-paths/laptops-and-desktops/win_on_arm_build_onnxruntime/_index.md
  content/learning-paths/laptops-and-desktops/win_on_arm_build_onnxruntime/_next-steps.md
Labels: tech_review

#1840 microbenchmarking-disk-performance-with-FIO-LP
  content/learning-paths/servers-and-cloud-computing/disk-io-benchmark/EBS.png
  content/learning-paths/servers-and-cloud-computing/disk-io-benchmark/IOPS.png
  content/learning-paths/servers-and-cloud-computing/disk-io-benchmark/_index.md
  content/learning-paths/servers-and-cloud-computing/disk-io-benchmark/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/disk-io-benchmark/characterising-workload.md
  content/learning-paths/servers-and-cloud-computing/disk-io-benchmark/diskio.jpeg
  content/learning-paths/servers-and-cloud-computing/disk-io-benchmark/introduction.md
  content/learning-paths/servers-and-cloud-computing/disk-io-benchmark/using-fio.md
  content/learning-paths/servers-and-cloud-computing/disk-io-benchmark/visualisations.png
Labels: ACM, awaiting_tech_review

#1827 LP ONNX Runtime on WoA
  content/learning-paths/laptops-and-desktops/win_python/intro.md
  content/learning-paths/laptops-and-desktops/win_python_onnx/_index.md
  content/learning-paths/laptops-and-desktops/win_python_onnx/_next-steps.md
  content/learning-paths/laptops-and-desktops/win_python_onnx/figures/01.png
  content/learning-paths/laptops-and-desktops/win_python_onnx/implementation.md
  content/learning-paths/laptops-and-desktops/win_python_onnx/inference.md
  content/learning-paths/laptops-and-desktops/win_python_onnx/intro.md
Labels: awaiting_tech_review

#1820 Update APS LP and install guide
  content/install-guides/ams.md
  content/learning-paths/mobile-graphics-and-gaming/ams/_index.md
  content/learning-paths/mobile-graphics-and-gaming/ams/ams.md
  content/learning-paths/mobile-graphics-and-gaming/ams/fa.md
  content/learning-paths/mobile-graphics-and-gaming/ams/ga.md
  content/learning-paths/mobile-graphics-and-gaming/ams/images/rd_capture_controls.png
  content/learning-paths/mobile-graphics-and-gaming/ams/images/rd_event_browser.png
  content/learning-paths/mobile-graphics-and-gaming/ams/images/rd_full_ui.png
  content/learning-paths/mobile-graphics-and-gaming/ams/images/rd_replay_context.png
  content/learning-paths/mobile-graphics-and-gaming/ams/malioc.md
  content/learning-paths/mobile-graphics-and-gaming/ams/pa.md
  content/learning-paths/mobile-graphics-and-gaming/ams/renderdoc.md
  content/learning-paths/mobile-graphics-and-gaming/ams/setup_tasks.md
  content/learning-paths/mobile-graphics-and-gaming/ams/streamline.md
  content/learning-paths/mobile-graphics-and-gaming/ams/supporting_tools.md
  content/learning-paths/smartphones-and-mobile/ams/images/rd_capture_controls.png
  content/learning-paths/smartphones-and-mobile/ams/images/rd_replay_context.png
  content/learning-paths/smartphones-and-mobile/ams/renderdoc.md
Labels: awaiting_tech_review

#1884 LP-Profile-Guided-Optimisation-and-Google-Benchmark
  content/learning-paths/servers-and-cloud-computing/cpp-profile-guided-optimisation/_index.md
  content/learning-paths/servers-and-cloud-computing/cpp-profile-guided-optimisation/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/cpp-profile-guided-optimisation/after-pgo.gif
  content/learning-paths/servers-and-cloud-computing/cpp-profile-guided-optimisation/before-pgo.gif
  content/learning-paths/servers-and-cloud-computing/cpp-profile-guided-optimisation/how-to-1.md
  content/learning-paths/servers-and-cloud-computing/cpp-profile-guided-optimisation/how-to-2.md
  content/learning-paths/servers-and-cloud-computing/cpp-profile-guided-optimisation/how-to-3.md
  content/learning-paths/servers-and-cloud-computing/cpp-profile-guided-optimisation/how-to-4.md
  content/learning-paths/servers-and-cloud-computing/cpp-profile-guided-optimisation/how-to-5.md
Labels: ACM, awaiting_tech_review

#1893 ONNX Learning Path
  content/learning-paths/servers-and-cloud-computing/onnx/_index.md
  content/learning-paths/servers-and-cloud-computing/onnx/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/onnx/analysis.md
  content/learning-paths/servers-and-cloud-computing/onnx/chatbot.md
  content/learning-paths/servers-and-cloud-computing/onnx/image_output.png
  content/learning-paths/servers-and-cloud-computing/onnx/output.png
  content/learning-paths/servers-and-cloud-computing/onnx/server.png
  content/learning-paths/servers-and-cloud-computing/onnx/setup.md
Labels: ACM, awaiting_tech_review
