Repository ArmDeveloperEcosystem/arm-learning-paths, pull requests merged in 2025-09, with the labels that each got.

#2268 Zena CSS debug with Arm DS
  content/learning-paths/automotive/zenacssdebug/_index.md
  content/learning-paths/automotive/zenacssdebug/_next-steps.md
  content/learning-paths/automotive/zenacssdebug/config.md
  content/learning-paths/automotive/zenacssdebug/configdb.png
  content/learning-paths/automotive/zenacssdebug/connect.md
  content/learning-paths/automotive/zenacssdebug/debugger_commands.png
  content/learning-paths/automotive/zenacssdebug/launch.md
  content/learning-paths/automotive/zenacssdebug/primarycompute.md
  content/learning-paths/automotive/zenacssdebug/rse.md
  content/learning-paths/automotive/zenacssdebug/safetyisland.md
  content/learning-paths/automotive/zenacssdebug/zena.md
Labels: tech_review

#2271 IRQ tuning guide
  content/learning-paths/servers-and-cloud-computing/irq-tuning-guide/_index.md
  content/learning-paths/servers-and-cloud-computing/irq-tuning-guide/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/irq-tuning-guide/checking.md
  content/learning-paths/servers-and-cloud-computing/irq-tuning-guide/conclusion.md
  content/learning-paths/servers-and-cloud-computing/irq-tuning-guide/patterns.md
Labels: ACM, tech_review

#2281 Add a new learning path on SIMD Loops.
  assets/contributors.csv
  content/learning-paths/cross-platform/simd-loops/1-about.md
  content/learning-paths/cross-platform/simd-loops/2-using.md
  content/learning-paths/cross-platform/simd-loops/3-example.md
  content/learning-paths/cross-platform/simd-loops/4-conclusion.md
  content/learning-paths/cross-platform/simd-loops/_index.md
  content/learning-paths/cross-platform/simd-loops/_next-steps.md
  content/learning-paths/mobile-graphics-and-gaming/ai-camera-pipelines/3-build.md
Labels: tech_review

#2208 Deploy Nginx on the Microsoft Azure Cobalt 100 processors
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/_index.md
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/backgroud.md
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/baseline.md
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/benchmarking.md
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/deploy.md
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/images/final-vm.png
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/images/instance.png
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/images/instance1.png
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/images/instance4.png
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/images/nginx-browser.png
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/images/nginx-web.png
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/images/ubuntu-pro.png
  content/learning-paths/servers-and-cloud-computing/nginx-on-azure/instance.md
Labels: ACM, tech_review

#2238 Deploy Golang on the Microsoft Azure Cobalt 100 processors
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/_index.md
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/background.md
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/baseline-testing.md
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/benchmarking.md
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/create-instance.md
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/deploy.md
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/images/final-vm.png
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/images/go-web.png
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/images/instance.png
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/images/instance1.png
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/images/instance4.png
  content/learning-paths/servers-and-cloud-computing/golang-on-azure/images/ubuntu-pro.png
Labels: ACM, tech_review

#1814 LPs on Halide
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/01.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/02.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/03.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/04.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/05.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/06.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/07.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/08.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/09.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/Figures/10.png
  content/learning-paths/mobile-graphics-and-gaming/android_halide/_index.md
  content/learning-paths/mobile-graphics-and-gaming/android_halide/_next-steps.md
  content/learning-paths/mobile-graphics-and-gaming/android_halide/android.md
  content/learning-paths/mobile-graphics-and-gaming/android_halide/aot-and-cross-compilation.md
  content/learning-paths/mobile-graphics-and-gaming/android_halide/fusion.md
  content/learning-paths/mobile-graphics-and-gaming/android_halide/intro.md
  content/learning-paths/mobile-graphics-and-gaming/android_halide/processing-workflow.md
Labels: tech_review

#2346 Compare Arm and x86 top-down performance analysis
  content/learning-paths/cross-platform/topdown-compare/1-top-down.md
  content/learning-paths/cross-platform/topdown-compare/2-code-examples.md
  content/learning-paths/cross-platform/topdown-compare/_index.md
  content/learning-paths/cross-platform/topdown-compare/_next-steps.md
Labels: ACM, editorial_review

#2349 Initial version of Windows on Arm VM Learning Path
  content/learning-paths/laptops-and-desktops/win11-vm-automation/_index.md
  content/learning-paths/laptops-and-desktops/win11-vm-automation/_next-steps.md
  content/learning-paths/laptops-and-desktops/win11-vm-automation/images/win11arm.png
  content/learning-paths/laptops-and-desktops/win11-vm-automation/prerequisites-1.md
  content/learning-paths/laptops-and-desktops/win11-vm-automation/understanding-scripts-2.md
  content/learning-paths/laptops-and-desktops/win11-vm-automation/vm-creation-3.md
  content/learning-paths/laptops-and-desktops/win11-vm-automation/vm-execution-4.md
Labels: tech_review

#2260 Deploy MySQL on the Microsoft Azure Cobalt 100 processors
  content/learning-paths/servers-and-cloud-computing/mysql-azure/_index.md
  content/learning-paths/servers-and-cloud-computing/mysql-azure/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/mysql-azure/background.md
  content/learning-paths/servers-and-cloud-computing/mysql-azure/baseline.md
  content/learning-paths/servers-and-cloud-computing/mysql-azure/benchmarking.md
  content/learning-paths/servers-and-cloud-computing/mysql-azure/create-instance.md
  content/learning-paths/servers-and-cloud-computing/mysql-azure/deploy.md
  content/learning-paths/servers-and-cloud-computing/mysql-azure/images/final-vm.png
  content/learning-paths/servers-and-cloud-computing/mysql-azure/images/instance.png
  content/learning-paths/servers-and-cloud-computing/mysql-azure/images/instance1.png
  content/learning-paths/servers-and-cloud-computing/mysql-azure/images/instance4.png
  content/learning-paths/servers-and-cloud-computing/mysql-azure/images/ubuntu-pro.png
Labels: ACM, tech_review
