Repository ArmDeveloperEcosystem/arm-learning-paths, pull requests merged in 2025-08, with the labels that each got.

#2219 Add LPs on neural graphics
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/1-install-plugin.md
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/2-emulation-layer.md
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/3-run-example.md
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/5-renderdoc.md
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/6-wrapping-up.md
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/_index.md
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/_next-steps.md
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/add_plugin_folder.png
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/confirm_layers.png
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/load_layers.png
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/nss_debug.png
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/renderdoc.png
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/renderdoc_plugin_ue.png
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/targeted_rhis.png
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/unreal_startup.png
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/verify_layers.png
  content/learning-paths/mobile-graphics-and-gaming/nss-unreal/images/verify_plugin_enabled.png
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/1-introduction.md
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/2-ml-ext-for-vulkan.md
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/3-first-sample.md
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/4-scenario-runner.md
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/5-renderdoc.md
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/6-wrapping-up.md
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/_index.md
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/_next-steps.md
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/images/load_layers.png
  content/learning-paths/mobile-graphics-and-gaming/vulkan-ml-sample/images/verify_layers.png
Labels: ready_to_publish

#2151 Add Privacy-First LLM Smart Home System for Raspberry Pi 5
  content/install-guides/llm-jetson-xavier.md
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/UI3.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/_index.md
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/_next-steps.md
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/benchmarks.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/cmd.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/cmd_stats.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/deepseek.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/example-picture.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/gemma2.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/hardware.jpeg
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/hardware2.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/how-to-1.md
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/how-to-2.md
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/how-to-3.md
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/sec1.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/security.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/security2.png
  content/learning-paths/embedded-and-microcontrollers/raspberry-pi-smart-home/stats3.png
Labels: tech_review

#2177 Deploy Apache Spark on Google Axion C4A virtual machine
  content/learning-paths/servers-and-cloud-computing/spark-on-gcp/_index.md
  content/learning-paths/servers-and-cloud-computing/spark-on-gcp/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/spark-on-gcp/background.md
  content/learning-paths/servers-and-cloud-computing/spark-on-gcp/baseline.md
  content/learning-paths/servers-and-cloud-computing/spark-on-gcp/benchmarking.md
  content/learning-paths/servers-and-cloud-computing/spark-on-gcp/image1.png
  content/learning-paths/servers-and-cloud-computing/spark-on-gcp/instance.md
  content/learning-paths/servers-and-cloud-computing/spark-on-gcp/spark-deployment.md
Labels: ACM, awaiting_tech_review

#2191 Run Spark applications on the Microsoft Azure Cobalt 100 processors
  content/learning-paths/servers-and-cloud-computing/spark-on-azure/_index.md
  content/learning-paths/servers-and-cloud-computing/spark-on-azure/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/spark-on-azure/background.md
  content/learning-paths/servers-and-cloud-computing/spark-on-azure/baseline.md
  content/learning-paths/servers-and-cloud-computing/spark-on-azure/benchmarking.md
  content/learning-paths/servers-and-cloud-computing/spark-on-azure/container-setup.md
  content/learning-paths/servers-and-cloud-computing/spark-on-azure/create-instance.md
  content/learning-paths/servers-and-cloud-computing/spark-on-azure/deploy.md
  content/learning-paths/servers-and-cloud-computing/spark-on-azure/instance-new.png
Labels: ACM, tech_review

#2197 New learning path: Deploy Arcee AFM-4.5B on Google Axion - final version
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/00_overview.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/01_launching_an_axion_instance.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/02_setting_up_the_instance.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/03_building_llama_cpp.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/04_install_python_dependencies_for_llama_cpp.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/05_downloading_and_optimizing_afm45b.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/06_running_inference.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/07_evaluating_the_quantized_models.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/08_conclusion.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/_index.md
  content/learning-paths/servers-and-cloud-computing/arcee-foundation-model-on-gcp/_next-steps.md
Labels: ACM, tech_review

#2190 Add CCA Trustee Learning Path
  content/learning-paths/servers-and-cloud-computing/cca-trustee/_index.md
  content/learning-paths/servers-and-cloud-computing/cca-trustee/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/cca-trustee/attestation-services.png
  content/learning-paths/servers-and-cloud-computing/cca-trustee/cca-trustee.md
  content/learning-paths/servers-and-cloud-computing/cca-trustee/flow.md
  content/learning-paths/servers-and-cloud-computing/cca-trustee/trustee.png
Labels: tech_review

#2216 Deploy MongoDB on Google Axion C4A virtual machine
  content/learning-paths/servers-and-cloud-computing/mongodb-on-gcp/_index.md
  content/learning-paths/servers-and-cloud-computing/mongodb-on-gcp/_next-steps.md
  content/learning-paths/servers-and-cloud-computing/mongodb-on-gcp/background.md
  content/learning-paths/servers-and-cloud-computing/mongodb-on-gcp/baseline-testing.md
  content/learning-paths/servers-and-cloud-computing/mongodb-on-gcp/benchmarking.md
  content/learning-paths/servers-and-cloud-computing/mongodb-on-gcp/create-instance.md
  content/learning-paths/servers-and-cloud-computing/mongodb-on-gcp/image1.png
  content/learning-paths/servers-and-cloud-computing/mongodb-on-gcp/mongodb-deploy.md
Labels: ACM, tech_review
